### ISSUE TITLE
[FEATURE] - Add ability to make clones

### ISSUE THREAD

**Issue by TheAnonymous88** [Black-Bulls-Bots/zerotwobot#15]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
add ability to make clones like in group help, these clones will have same commands as Zero Two but they will have different pfp and Name.

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by jk6521** [comment]
will sure make this feature

**Comment by TheAnonymous88** [comment]
> will sure make this feature

thx
