### ISSUE TITLE
support spoiler formatting.

### ISSUE THREAD

**Issue by jk6521** [Black-Bulls-Bots/zerotwobot#19]
Telegram released new [update](https://t.me/telegram/161) today which has spoiler formatting option.

syntax - || test ||

User's can use spoiler while saving filter and notes.

**Comment by ronny8877** [comment]
![bitmoji](https://sdk.bitmoji.com/render/panel/354a9cb2-5018-4be5-9679-20eaa229d133-dfb0bf5c-ca39-41be-8163-8fd8be5e8b78-v1.png?transparent=1&palette=1&width=246)
i see

**Comment by jk6521** [comment]
Fixed in 75409420c32cca8f565f7491df7dc1f73500718b
